import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import validate_skills  # noqa: E402

SKILLS = ROOT / "skills"
MAKE = {
    "creative-ideation": ["concept-frameworks.md", "ad-type-playbook.md"],
    "hook-writer": ["hook-archetypes.md", "hook-checklist.md"],
    "persona-builder": ["persona-template.md"],
    "creative-brief": ["brief-template.md", "creator-brief-template.md"],
}
BRIEF_SECTIONS = [
    "Objective", "Persona and stage", "Single message", "Proof", "Offer and dates", "Ad type",
    "Format, placements and specs", "Hook", "Script or shot list", "On-screen text", "Visual direction",
    "Casting direction", "Tone", "Hero line, supporting line and CTA", "Mandatories and must-avoids",
    "Naming per deliverable", "How it will be judged", "Evidence",
]
EXAMPLE_MARKER = "Example output for a fictional brand. Generated by following the skill; not real data."
EXAMPLES = ("ideas.md", "hooks.md", "personas.md", "brief.md")
SKILL_AND_REFERENCE_FILES = [p for name in MAKE for p in
                             [SKILLS / name / "SKILL.md"] + sorted((SKILLS / name / "references").glob("*.md"))]


class MakeSkillStructureTest(unittest.TestCase):
    def test_each_skill_has_spec_only_frontmatter(self):
        for name in MAKE:
            with self.subTest(skill=name):
                self.assertEqual(validate_skills.validate_skill(SKILLS / name / "SKILL.md"), [])

    def test_each_skill_has_its_references(self):
        for name, refs in MAKE.items():
            for ref in refs:
                with self.subTest(skill=name, ref=ref):
                    self.assertTrue((SKILLS / name / "references" / ref).is_file())

    def test_every_reference_is_linked_from_its_skill(self):
        for name, refs in MAKE.items():
            body = (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")
            for ref in refs:
                with self.subTest(skill=name, ref=ref):
                    self.assertIn("references/" + ref, body)

    def test_each_skill_names_the_next_step_and_a_guardrails_section(self):
        for name in MAKE:
            body = (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")
            with self.subTest(skill=name):
                self.assertIn("## Before you start", body)
                self.assertIn("## Guardrails", body)
                self.assertIn("Next step", body)
                self.assertIn("advertising law", body)

    def test_hook_archetypes_has_at_least_twelve(self):
        text = (SKILLS / "hook-writer" / "references" / "hook-archetypes.md").read_text(encoding="utf-8")
        rows = re.findall(r"^\|\s*\d+\s*\|", text, flags=re.M)
        self.assertGreaterEqual(len(rows), 12)

    def test_brief_template_has_every_section(self):
        text = (SKILLS / "creative-brief" / "references" / "brief-template.md").read_text(encoding="utf-8")
        headings = re.findall(r"^## (.+)$", text, flags=re.M)
        for section in BRIEF_SECTIONS:
            with self.subTest(section=section):
                self.assertIn(section, headings)

    def test_persona_template_has_the_two_key_fields(self):
        text = (SKILLS / "persona-builder" / "references" / "persona-template.md").read_text(encoding="utf-8").lower()
        self.assertIn("awareness stage", text)
        self.assertIn("emotional starting state", text)

    def test_creator_brief_covers_rights_and_disclosure(self):
        text = (SKILLS / "creative-brief" / "references" / "creator-brief-template.md").read_text(encoding="utf-8").lower()
        for needle in ("usage rights", "paid use", "disclosure", "feedback rounds"):
            with self.subTest(needle=needle):
                self.assertIn(needle, text)

    def test_evidence_script_is_synced_beside_the_skill(self):
        self.assertTrue((SKILLS / "creative-brief" / "scripts" / "creative_metrics.py").is_file())


class NoBenchmarkTest(unittest.TestCase):
    def test_no_percent_figures(self):
        for path in SKILL_AND_REFERENCE_FILES:
            for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                with self.subTest(file=path.name, line=number):
                    self.assertIsNone(re.search(r"\d\s*%", line), line)

    def test_benchmark_only_appears_as_a_refusal(self):
        for path in SKILL_AND_REFERENCE_FILES:
            for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                for match in re.finditer(r"benchmark", line, flags=re.I):
                    before = line[max(0, match.start() - 40):match.start()].lower()
                    with self.subTest(file=path.name, line=number):
                        self.assertTrue(re.search(r"\b(no|never|not|without|nor)\b[^.]*$", before), line)



class ExampleFilesTest(unittest.TestCase):
    def test_each_example_starts_with_the_fictional_brand_marker(self):
        for name in EXAMPLES:
            path = ROOT / "examples" / "acme" / name
            with self.subTest(file=name):
                self.assertTrue(path.is_file())
                self.assertEqual(path.read_text(encoding="utf-8").splitlines()[0].strip("*_ "), EXAMPLE_MARKER)


if __name__ == "__main__":
    unittest.main()
